<?php

namespace ContainerXZuhb9Y;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EkHMA4HService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EkHMA4H' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\AuthorController::index' => ['privates', '.service_locator.AJ36o_l.App\\Controller\\Admin\\AuthorController::index()', 'getAuthorControllerindexService', true],
            'App\\Controller\\Admin\\AuthorController::new' => ['privates', '.service_locator.j86vcY0.App\\Controller\\Admin\\AuthorController::new()', 'getAuthorControllernewService', true],
            'App\\Controller\\Admin\\BookController::index' => ['privates', '.service_locator.P.Hw848.App\\Controller\\Admin\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\Admin\\BookController::new' => ['privates', '.service_locator.gW3X0WI.App\\Controller\\Admin\\BookController::new()', 'getBookControllernewService', true],
            'App\\Controller\\Admin\\EditorController::index' => ['privates', '.service_locator.N1Wj5LA.App\\Controller\\Admin\\EditorController::index()', 'getEditorControllerindexService', true],
            'App\\Controller\\Admin\\EditorController::new' => ['privates', '.service_locator.kaexKkG.App\\Controller\\Admin\\EditorController::new()', 'getEditorControllernewService', true],
            'App\\Controller\\BookController::index' => ['privates', '.service_locator.P.Hw848.App\\Controller\\BookController::index()', 'getBookControllerindex2Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\AuthorController:index' => ['privates', '.service_locator.AJ36o_l.App\\Controller\\Admin\\AuthorController::index()', 'getAuthorControllerindexService', true],
            'App\\Controller\\Admin\\AuthorController:new' => ['privates', '.service_locator.j86vcY0.App\\Controller\\Admin\\AuthorController::new()', 'getAuthorControllernewService', true],
            'App\\Controller\\Admin\\BookController:index' => ['privates', '.service_locator.P.Hw848.App\\Controller\\Admin\\BookController::index()', 'getBookControllerindexService', true],
            'App\\Controller\\Admin\\BookController:new' => ['privates', '.service_locator.gW3X0WI.App\\Controller\\Admin\\BookController::new()', 'getBookControllernewService', true],
            'App\\Controller\\Admin\\EditorController:index' => ['privates', '.service_locator.N1Wj5LA.App\\Controller\\Admin\\EditorController::index()', 'getEditorControllerindexService', true],
            'App\\Controller\\Admin\\EditorController:new' => ['privates', '.service_locator.kaexKkG.App\\Controller\\Admin\\EditorController::new()', 'getEditorControllernewService', true],
            'App\\Controller\\BookController:index' => ['privates', '.service_locator.P.Hw848.App\\Controller\\BookController::index()', 'getBookControllerindex2Service', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\AuthorController::index' => '?',
            'App\\Controller\\Admin\\AuthorController::new' => '?',
            'App\\Controller\\Admin\\BookController::index' => '?',
            'App\\Controller\\Admin\\BookController::new' => '?',
            'App\\Controller\\Admin\\EditorController::index' => '?',
            'App\\Controller\\Admin\\EditorController::new' => '?',
            'App\\Controller\\BookController::index' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\AuthorController:index' => '?',
            'App\\Controller\\Admin\\AuthorController:new' => '?',
            'App\\Controller\\Admin\\BookController:index' => '?',
            'App\\Controller\\Admin\\BookController:new' => '?',
            'App\\Controller\\Admin\\EditorController:index' => '?',
            'App\\Controller\\Admin\\EditorController:new' => '?',
            'App\\Controller\\BookController:index' => '?',
        ]);

        if (isset($container->privates['.service_locator.EkHMA4H'])) {
            return $container->privates['.service_locator.EkHMA4H'];
        }

        return $container->privates['.service_locator.EkHMA4H'] = $instance;
    }
}
