<?php

namespace ContainerFek088A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ZenstruckFoundry_ConfigurationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public '.zenstruck_foundry.configuration' shared service.
     *
     * @return \Zenstruck\Foundry\Configuration
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Configuration.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/FactoryRegistryInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/InMemory/InMemoryFactoryRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/FactoryRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/fakerphp/faker/src/Faker/Generator.php';
        include_once \dirname(__DIR__, 4).'/vendor/fakerphp/faker/src/Faker/Factory.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/Object/Instantiator.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/StoryRegistry.php';
        include_once \dirname(__DIR__, 4).'/vendor/zenstruck/foundry/src/InMemory/InMemoryRepositoryRegistry.php';

        return $container->services['.zenstruck_foundry.configuration'] = new \Zenstruck\Foundry\Configuration(new \Zenstruck\Foundry\InMemory\InMemoryFactoryRegistry(new \Zenstruck\Foundry\FactoryRegistry(new RewindableGenerator(fn () => new \EmptyIterator(), 0))), \Faker\Factory::create(), \Zenstruck\Foundry\Object\Instantiator::withConstructor(), new \Zenstruck\Foundry\StoryRegistry(new RewindableGenerator(function () use ($container) {
            yield 0 => ($container->privates['App\\Story\\AppStory'] ??= new \App\Story\AppStory());
        }, 1), []), ($container->privates['.zenstruck_foundry.persistence_manager'] ?? $container->load('get_ZenstruckFoundry_PersistenceManagerService')), true, NULL, $container->getEnv('default::int:FOUNDRY_FAKER_SEED'), new \Zenstruck\Foundry\InMemory\InMemoryRepositoryRegistry(($container->privates['.service_locator.dpiLQ5O'] ??= new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [], []))), NULL, false, ($container->services['event_dispatcher'] ?? self::getEventDispatcherService($container)));
    }
}
