<?php

namespace ContainerFek088A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorControllerindexService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AJ36o_l.App\Controller\Admin\AuthorController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AJ36o_l.App\\Controller\\Admin\\AuthorController::index()'] = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\AuthorRepository', 'getAuthorRepositoryService', true],
        ], [
            'repository' => 'App\\Repository\\AuthorRepository',
        ]))->withContext('App\\Controller\\Admin\\AuthorController::index()', $container);
    }
}
