<?php

namespace ContainerFek088A;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllerindex2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.P.Hw848.App\Controller\BookController::index()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.P.Hw848.App\\Controller\\BookController::index()'] = ($container->privates['.service_locator.P.Hw848'] ?? $container->load('get_ServiceLocator_P_Hw848Service'))->withContext('App\\Controller\\BookController::index()', $container);
    }
}
