<?php

namespace Container5VHZh8O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getAuthorControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.j86vcY0.App\Controller\Admin\AuthorController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = (new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'manager' => '?',
        ]))->withContext('App\\Controller\\Admin\\AuthorController::new()', $container);

        if (isset($container->privates['.service_locator.j86vcY0.App\\Controller\\Admin\\AuthorController::new()'])) {
            return $container->privates['.service_locator.j86vcY0.App\\Controller\\Admin\\AuthorController::new()'];
        }

        return $container->privates['.service_locator.j86vcY0.App\\Controller\\Admin\\AuthorController::new()'] = $instance;
    }
}
