<?php

namespace Container5VHZh8O;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getLastConnectionListenerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\EventListener\LastConnectionListener' shared autowired service.
     *
     * @return \App\EventListener\LastConnectionListener
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/src/EventListener/LastConnectionListener.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\EventListener\\LastConnectionListener'])) {
            return $container->privates['App\\EventListener\\LastConnectionListener'];
        }

        $instance = new \App\EventListener\LastConnectionListener($a);

        if (isset($container->privates['App\\EventListener\\LastConnectionListener'])) {
            return $container->privates['App\\EventListener\\LastConnectionListener'];
        }

        return $container->privates['App\\EventListener\\LastConnectionListener'] = $instance;
    }
}
