<?php

namespace ContainerCx9nqVj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Fms9SjnService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.fms9Sjn' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\AuthorController::new' => ['privates', '.service_locator.DtKQrXP.App\\Controller\\Admin\\AuthorController::new()', 'getAuthorControllernewService', true],
            'App\\Controller\\Admin\\BookController::new' => ['privates', '.service_locator.DtKQrXP.App\\Controller\\Admin\\BookController::new()', 'getBookControllernewService', true],
            'App\\Controller\\Admin\\EditorController::new' => ['privates', '.service_locator.DtKQrXP.App\\Controller\\Admin\\EditorController::new()', 'getEditorControllernewService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B.kernel::registerContainerConfiguration()', 'get_ServiceLocator_1vYpZ1B_KernelregisterContainerConfigurationService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B.kernel::loadRoutes()', 'get_ServiceLocator_1vYpZ1B_KernelloadRoutesService', true],
            'App\\Controller\\Admin\\AuthorController:new' => ['privates', '.service_locator.DtKQrXP.App\\Controller\\Admin\\AuthorController::new()', 'getAuthorControllernewService', true],
            'App\\Controller\\Admin\\BookController:new' => ['privates', '.service_locator.DtKQrXP.App\\Controller\\Admin\\BookController::new()', 'getBookControllernewService', true],
            'App\\Controller\\Admin\\EditorController:new' => ['privates', '.service_locator.DtKQrXP.App\\Controller\\Admin\\EditorController::new()', 'getEditorControllernewService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\Admin\\AuthorController::new' => '?',
            'App\\Controller\\Admin\\BookController::new' => '?',
            'App\\Controller\\Admin\\EditorController::new' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\Admin\\AuthorController:new' => '?',
            'App\\Controller\\Admin\\BookController:new' => '?',
            'App\\Controller\\Admin\\EditorController:new' => '?',
        ]);

        if (isset($container->privates['.service_locator.fms9Sjn'])) {
            return $container->privates['.service_locator.fms9Sjn'];
        }

        return $container->privates['.service_locator.fms9Sjn'] = $instance;
    }
}
