<?php

namespace ContainerCx9nqVj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DtKQrXPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DtKQrXP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'manager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'manager' => '?',
        ]);

        if (isset($container->privates['.service_locator.DtKQrXP'])) {
            return $container->privates['.service_locator.DtKQrXP'];
        }

        return $container->privates['.service_locator.DtKQrXP'] = $instance;
    }
}
