<?php

namespace ContainerCx9nqVj;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getBookControllernewService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DtKQrXP.App\Controller\Admin\BookController::new()' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $a = ($container->privates['.service_locator.DtKQrXP'] ?? $container->load('get_ServiceLocator_DtKQrXPService'));

        if (isset($container->privates['.service_locator.DtKQrXP.App\\Controller\\Admin\\BookController::new()'])) {
            return $container->privates['.service_locator.DtKQrXP.App\\Controller\\Admin\\BookController::new()'];
        }

        $instance = $a->withContext('App\\Controller\\Admin\\BookController::new()', $container);

        if (isset($container->privates['.service_locator.DtKQrXP.App\\Controller\\Admin\\BookController::new()'])) {
            return $container->privates['.service_locator.DtKQrXP.App\\Controller\\Admin\\BookController::new()'];
        }

        return $container->privates['.service_locator.DtKQrXP.App\\Controller\\Admin\\BookController::new()'] = $instance;
    }
}
