<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZpZ7RDK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZpZ7RDK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZpZ7RDK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZpZ7RDK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZpZ7RDK\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZpZ7RDK',
    'container.build_id' => 'a23e5232',
    'container.build_time' => 1769156879,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZpZ7RDK');
