<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFZxAN4E\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFZxAN4E/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerFZxAN4E.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerFZxAN4E\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerFZxAN4E\App_KernelDevDebugContainer([
    'container.build_hash' => 'FZxAN4E',
    'container.build_id' => '85991815',
    'container.build_time' => 1768926478,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFZxAN4E');
